adapter: CsvAdapter
adapters:
        - MySqlAdapter:
                host: localhost
                username: <your-username>
                password: <your-password>
custom_routes:
        'sample/route':
                controller: TestController
                action: TestAction